# Generated by Django 2.0.5 on 2018-06-29 05:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Força', 'Força'), ('Destreza', 'Destreza'), ('Constituição', 'Constituição'), ('Inteligência', 'Inteligência'), ('Sabedoria', 'Sabedoria'), ('Carisma', 'Carisma')], max_length=12, unique=True)),
                ('slug', models.CharField(choices=[('for', 'for'), ('des', 'des'), ('con', 'con'), ('int', 'int'), ('sab', 'sab'), ('car', 'car')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('valor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('qualidade', models.CharField(choices=[('boa', 'BBA Boa'), ('ruim', 'BBA Ruim')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('quantidade_pericias_por_nivel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dv', models.IntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')])),
                ('conjurador', models.CharField(choices=[('div', 'Divino'), ('arc', 'Arcano'), ('nan', 'Não conjurador')], default='nan', max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=37)),
                ('slug', models.CharField(max_length=37, unique=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('valor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('nome', models.CharField(choices=[('Fortitude', 'Fortitude'), ('Reflexo', 'Reflexo'), ('Vontade', 'Vontade')], max_length=9)),
                ('slug', models.CharField(choices=[('fort', 'fort'), ('ref', 'ref'), ('von', 'von')], max_length=4)),
                ('qualidade', models.CharField(choices=[('boa', 'Resistencia Boa'), ('ruim', 'Resistencia Ruim')], max_length=4)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Tendencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=16, unique=True)),
                ('slug', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassePrestigio',
            fields=[
                ('classe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Classe')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.classe',),
        ),
        migrations.AddField(
            model_name='classe',
            name='bbas',
            field=models.ManyToManyField(related_name='_classe_bbas_+', to='core.Bba'),
        ),
        migrations.AddField(
            model_name='classe',
            name='pericias',
            field=models.ManyToManyField(related_name='_classe_pericias_+', to='core.Pericia'),
        ),
        migrations.AddField(
            model_name='classe',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.classe_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='classe',
            name='resistencias',
            field=models.ManyToManyField(related_name='_classe_resistencias_+', to='core.Resistencia'),
        ),
        migrations.AddField(
            model_name='classe',
            name='tendencias',
            field=models.ManyToManyField(related_name='_classe_tendencias_+', to='core.Tendencia'),
        ),
        migrations.AlterUniqueTogether(
            name='bba',
            unique_together={('qualidade', 'nivel', 'valor')},
        ),
        migrations.AlterUniqueTogether(
            name='resistencia',
            unique_together={('slug', 'qualidade', 'nivel', 'valor')},
        ),
    ]
