# Generated by Django 2.0.5 on 2018-07-04 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personagem.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=personagem.utils.get_personagem_upload_path)),
                ('pele', models.CharField(blank=True, max_length=10, null=True)),
                ('cabelos', models.CharField(blank=True, max_length=10, null=True)),
                ('olhos', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1)),
                ('tamanho', models.CharField(choices=[('mi', 'Minúsculo'), ('di', 'Diminuto'), ('mu', 'Miúdo'), ('pe', 'Pequeno'), ('me', 'Médio'), ('gr', 'Grande'), ('en', 'Enorme'), ('im', 'Imenso'), ('co', 'Colossal')], max_length=2)),
                ('lore', models.TextField(blank=True, null=True)),
                ('arco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='campanha.Arco')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemAtributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('valor_temporario', models.IntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Atributo')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='personagem.Personagem')),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Classe')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='personagem.Personagem')),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Modelo')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='personagem.Personagem')),
            ],
        ),
        migrations.AddField(
            model_name='personagem',
            name='lista_atributos',
            field=models.ManyToManyField(related_name='_personagem_lista_atributos_+', through='personagem.PersonagemAtributo', to='core.Atributo'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='lista_classes',
            field=models.ManyToManyField(related_name='_personagem_lista_classes_+', through='personagem.PersonagemClasse', to='core.Classe'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='lista_modelos',
            field=models.ManyToManyField(blank=True, related_name='_personagem_lista_modelos_+', through='personagem.PersonagemModelo', to='core.Modelo'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Raca'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='tendencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Tendencia'),
        ),
        migrations.AlterUniqueTogether(
            name='personagemmodelo',
            unique_together={('personagem', 'modelo')},
        ),
        migrations.AlterUniqueTogether(
            name='personagemclasse',
            unique_together={('personagem', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='personagematributo',
            unique_together={('personagem', 'atributo')},
        ),
        migrations.AlterUniqueTogether(
            name='personagem',
            unique_together={('jogador', 'nome')},
        ),
    ]
